### ISSUE TITLE
After about 5 minutes of processing, function will timeout and cancel.

### ISSUE THREAD

**Issue by raphael-liming** [shibayan/keyvault-acmebot#128]
2020-07-06T17:36:22Z   [Error]   Executed 'Dns01Authorization' (Failed, Id=fb6ea836-493a-40bd-af16-478784350bd1)
2020-07-06T17:36:22Z   [Error]   6a8b1cbd7b844dc5bcc013a96a6dbc0f:27: Function 'Dns01Authorization (Activity)' failed with an error. Reason: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Management.Dns.ZonesOperations.ListNextWithHttpMessagesAsync(String nextPageLink, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Dns.ZonesOperationsExtensions.ListNextAsync(IZonesOperations operations, String nextPageLink, CancellationToken cancellationToken)
   at KeyVault.Acmebot.Internal.AzureSdkExtensions.ListAllAsync(IZonesOperations operations) in D:\a\1\s\KeyVault.Acmebot\Internal\AzureSdkExtensions.cs:line 23
   at KeyVault.Acmebot.SharedFunctions.Dns01Authorization(String[] authorizationUrls) in D:\a\1\s\KeyVault.Acmebot\SharedFunctions.cs:line 154
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 468
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 322
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 117. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: asc-certificates. SlotName: Production. ExtensionVersion: 2.1.1. SequenceNumber: 889.
2020-07-06T17:36:22Z   [Information]   Executing 'IssueCertificate' (Reason='', Id=fe614c36-281d-4d0e-9530-662be02c03ae)
2020-07-06T17:36:29Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:36:29Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0244ms - processed: 1 items - remaining: 0 items
2020-07-06T17:36:33Z   [Verbose]   HttpMessageHandler expired after 120000ms for client ''
2020-07-06T17:36:43Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:36:43Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0013ms - processed: 0 items - remaining: 1 items
2020-07-06T17:36:53Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:36:53Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0011ms - processed: 0 items - remaining: 1 items
2020-07-06T17:37:03Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:37:03Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0012ms - processed: 0 items - remaining: 1 items
2020-07-06T17:37:13Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:37:13Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0016ms - processed: 0 items - remaining: 1 items
2020-07-06T17:37:23Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:37:23Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0012ms - processed: 0 items - remaining: 1 items
2020-07-06T17:37:33Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:37:33Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0012ms - processed: 0 items - remaining: 1 items
2020-07-06T17:37:43Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:37:43Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0018ms - processed: 0 items - remaining: 1 items
2020-07-06T17:37:53Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:37:53Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0011ms - processed: 0 items - remaining: 1 items
2020-07-06T17:38:03Z   [Verbose]   Starting HttpMessageHandler cleanup cycle with 1 items
2020-07-06T17:38:03Z   [Verbose]   Ending HttpMessageHandler cleanup cycle after 0.0122ms - processed: 0 items - remaining: 1 items

**Comment by raphael-liming** [comment]
Further info: I manage a lot of certificates, so I redeployed the function to an app service plan (instead of consumption plan) to get around the built-in 5 minute timeout of azure functions (in case that was the issue). I'm having trouble diagnosing if the issue is coming from the orchestrator sending the command to cancel, or if it has to do with that built-in time limit of 5 minutes (which should now default to 30 minutes since I'm now running on an app service plan)

**Comment by shibayan** [comment]
Although implemented to scale, we manage a large number of certificates in a single key vault It is not designed to do so. You need to do things like deploy multiple instance.
