### ISSUE TITLE
Renewal is failing but only for some domains

### ISSUE THREAD

**Issue by AviateX14** [shibayan/keyvault-acmebot#157]
I have KeyVault AcmeBot setup to renew SSL certificates for around 15 certificates, but some of them are failing. The failure is not intermittent, and trying to renew the certificate('s) in question manually or automatically fails. 

The function app has access to the Azure DNS resources (Zone contributor rights).

The following is written to app insights during a renewal attempt:

```
c4095cbf3d4f459d83d50c89b9423278: Function 'IssueCertificate (Orchestrator)' failed with an error. Reason: Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionFailedException: The activity function 'CheckDnsChallenge' failed: "Unknown Error". See the function execution logs for additional details.
 ---> DnsClient.DnsResponseException: Unknown Error
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 702
   at KeyVault.Acmebot.SharedFunctions.IssueCertificate(IDurableOrchestrationContext context) in /home/runner/work/keyvault-acmebot/keyvault-acmebot/KeyVault.Acmebot/SharedFunctions.cs:line 68
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.InvokeUserCodeAndHandleResults(RegisteredFunctionInfo orchestratorInfo, OrchestrationContext innerContext) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 150. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: ks-fa-3sq-ssl-rizo. SlotName: Production. ExtensionVersion: 2.3.0. SequenceNumber: 27. TaskEventId: -1
```

Elsewhere there are logs suggesting it's timing out somewhere:

```
c4095cbf3d4f459d83d50c89b9423278: Function 'CheckDnsChallenge (Activity)' failed with an error. Reason: DnsClient.DnsResponseException: Query 40818 => _acme-challenge.www.redacted.io IN TXT on 100.76.184.23:53 timed out or is a transient error.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.Tasks.TaskExtensions.WithCancellation[T](Task`1 task, CancellationToken cancellationToken, Action onCancel)
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   at DnsClient.LookupClient.QueryInternalAsync(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers, CancellationToken cancellationToken)
   at KeyVault.Acmebot.SharedFunctions.CheckDnsChallenge(IList`1 challengeResults) in /home/runner/work/keyvault-acmebot/keyvault-acmebot/KeyVault.Acmebot/SharedFunctions.cs:line 210
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 589
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 537
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 481
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 290. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: ks-fa-3sq-ssl-rizo. SlotName: Production. ExtensionVersion: 2.3.0. SequenceNumber: 26. TaskEventId: 3
```

And elsewhere...
```
91b8eba7b1b84033a33a6c6c77433ffe: Function 'CheckIsReady (Activity)' failed with an error. Reason: KeyVault.Acmebot.Internal.RetriableActivityException: ACME domain validation is pending.
   at KeyVault.Acmebot.SharedFunctions.CheckIsReady(OrderDetails orderDetails) in /home/runner/work/keyvault-acmebot/keyvault-acmebot/KeyVault.Acmebot/SharedFunctions.cs:line 240
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 589
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 537
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 481
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 290. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: ks-fa-3sq-ssl-rizo. SlotName: Production. ExtensionVersion: 2.3.0. SequenceNumber: 34. TaskEventId: 5
```

**Comment by shibayan** [comment]
Make sure the failing domain name servers are using a supported service such as Azure DNS or Cloudflare. It appears that the domains listed in the log are using name servers that are not supported.

However, the behavior when a query to DNS times out is a glitch, so we'll fix that separately.

This application uses exceptions for managed retries, so some exceptions (`RetriableActivityException`) are logged but are normal. I are considering filtering in the future.

**Comment by AviateX14** [comment]
Ah, complete goof on my part. Thanks for the spot, I had setup the NS records in cloudflare to point to Azure, but they were to the wrong name servers. Amazed it ever worked.

Regarding the retriable errors, I also got a spate of these in auto renewals that did succeed, I assume they fall into this category?

```
Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionFailedException: The activity function 'CheckIsReady' failed: "Invalid order status. Required retry at first.". See the function execution logs for additional details.
---> System.InvalidOperationException: Invalid order status. Required retry at first.
  at KeyVault.Acmebot.SharedFunctions.CheckIsReady(OrderDetails orderDetails) in /home/runner/work/keyvault-acmebot/keyvault-acmebot/KeyVault.Acmebot/SharedFunctions.cs:line 237
```

**Comment by AviateX14** [comment]
It's worth noting the order of events here, first this occurs:

`Exception while executing function: CheckIsReady ACME domain validation is pending.` (KeyVault.Acmebot.Internal.RetriableActivityException)

Followed by:

`The orchestrator function 'IssueCertificate' failed: "The activity function 'CheckIsReady' failed: "Invalid order status. Required retry at first.". See the function execution logs for additional details.". See the function execution logs for additional details.` (System.InvalidOperationException)

The name servers for this wildcard cert are correctly configured. 

From this it looks like the first operation fails due to awaiting validation from LetsEncrypt - but schedules a retry, and that the second operation then comes along and tries to renew the cert and fails because the retry hasn't happened yet?

**Comment by shibayan** [comment]
An invalid order status is returned if the verification on Let's Encrypt side fails. You have to make sure that the record "_acme-challenge" is correctly retrieved.

I checked the operation with the latest version and there was no problem. There is a possibility that it may take some time for the name server settings to be reflected.

**Comment by AviateX14** [comment]
In this case the name server records have been configured for some weeks and and requests to the domain('s) in question - with the records being hosted in Azure - work as expected. I can do an nslookup to retrieve the acme challenge record, presumably when the cert renewal runs the record doesn't propogate fast enough for LetsEncrypt to see it before the timeout in KeyVault-AcmeBot is exceeded? If I manually renew (via /renew-certificate) it works, but sometimes only on the second attempt.

**Comment by shibayan** [comment]
I can't keep up with your understanding of the problem, so please sort it out.

- Is it working?
- Type of certificate (wildcard / SANs / both)
- Type of DNS Provider
- If it doesn't work, is it an automatic or manual update?

If the Let's Encrypt validation fails while Acmebot's DNS record validation is successful, there may be a problem with the DNS server.

**Comment by Crossbow78** [comment]
I'm having the same issue: I see 4 times "**ACME domain validation is pending**" followed by an "**Invalid order status. Required retry at first**" in the logs.

Some context:
* I've seen it with two automated renewals
* It's a single subdomain (www) certificate
* My domain has been delegated to Azure DNS
* I'm seeing a fresh `_acme-challenge.www` TXT record in my DNS
* I can successfully query this record with nslookup (which confirms the previous two points)

The first time (two weeks ago) when it failed, I manually trigged the renew via the UI, and it succeeded.
The last time (yesterday) when it failed, I manually triggered the `RenewCertificates_Timer`  function, and it succeeded.

Does an ACME order perhaps expire when the DNS lookup fails for more than 60 seconds?

**Comment by AviateX14** [comment]
Apologies for the delay. For simplicity, my issue is identical to what @Crossbow78 described above, the only exception is that my certificate is a wildcard.

7 Days ago one of my certificates failed to automatically renew with the exact set of errors mentioned above. Today, the renewal was automatically retried and it succeeded. I haven’t changed anything in those 7 days. 

To answer your specific questions:
1. Is it working? No, not as it should. It requires either a manual renewal after the auto renewal fails, or to wait as I did above.
2. Type of certificate? Wildcard. 
3. Type of provider? Azure DNS. 
4. When it doesn’t work, is it an automated or manual renewal? Automated.

**Comment by shibayan** [comment]
Since the update a few days ago, I have improved the error messages and logging for order status being invalid, so you should be able to search term `ACME domain validation error` for the detailed cause of the failure from Application Insights.

Perhaps there is a lag between Acmebot and Let's Encrypt in resolving DNS records. This means that Acmebot can resolve the new record, but Let's Encrypt can't resolve it yet.

I are considering changes to resolve DNS records in Acmebot multiple times for stabilization, and to continue processing on successive successes.

**Comment by shibayan** [comment]
v3.3.5 Released
