### ISSUE TITLE
Error is certificate issuance if certificate with less number of DNS names is attempted for issuance

### ISSUE THREAD

**Issue by yarashagarwal** [shibayan/keyvault-acmebot#590]
**Describe the bug**

The certificate issuance fails with the following error:

Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: FinalizeOrder ---> ACMESharp.Protocol.AcmeProtocolException : Error finalizing order :: Order includes different number of names than CSR specifies
   at async ACMESharp.Protocol.AcmeProtocolClient.SendAcmeAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async ACMESharp.Protocol.AcmeProtocolClient.FinalizeOrderAsync(String orderFinalizeUrl,Byte[] derEncodedCsr,CancellationToken cancel)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async KeyVault.Acmebot.Functions.SharedActivity.FinalizeOrder(ValueTuple`2 input) at /home/runner/work/keyvault-acmebot/keyvault-acmebot/KeyVault.Acmebot/Functions/SharedActivity.cs : 386
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 581
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 527
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 306
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 352
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 108

**To Reproduce**
1. Create a certificate with DNS names : test1.xyz.com, test2.xyz.com and test3.xyz.com.
2. Issue the certificate to keyvault - The certificate issuance succeds.
3. Delete the old certificate from the keyvault and purge it.
4. Now issue a new certificate with 2 DNS names - test1.xyz.com and test2.xyz.com
5. Get the error and certificate issuance fails

**Environment (please complete the following information):**
 - Certificate Type: subdomain certificate - A SAN certificate with multiple domain names
 - Certificate Deploy Target: Azure KeyVault

**Comment by shibayan** [comment]
To change the DNS name, the Key Vault Certificate policy must be edited using Azure Portal. This behavior will be improved in the future.

**Comment by yarashagarwal** [comment]
Thanks for the reply. It worked with editing the certificate policy of the existing certificates or just deleting and purging the certificate and re-creating it.
