### ISSUE TITLE
Azure Function isn't able to add DNS records to certain zones

### ISSUE THREAD

**Issue by raphael-liming** [shibayan/keyvault-acmebot#61]
I've verified that my function has "DNS Zone Contributor" (I did it at the Subscription level since I operate over 1k zones) but I don't see the function inserting the appropriate DNS records into the zone, thus failing to validate the DNS record.  Working for most of my other DNS zones, I only have a few it doesn't work for. What diagnostic information can I provide? Unsure why it doesn't work.

**Comment by raphael-liming** [comment]
Example:

> IssueCertificate
Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionFailedException: The activity function 'CheckDnsChallenge' failed: "_acme-challenge.dlwww.tennesseematuredriver.com did not resolve.". See the function execution logs for additional details.
---> KeyVault.Acmebot.Internal.RetriableActivityException: _acme-challenge.dlwww.tennesseematuredriver.com did not resolve.
  at KeyVault.Acmebot.SharedFunctions.CheckDnsChallenge(ChallengeResult challenge) in D:\a\1\s\KeyVault.Acmebot\SharedFunctions.cs:line 227
  at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
  at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
  at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585
  at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532
  at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 468
  at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278
  --- End of inner exception stack trace ---
  at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 617
  at KeyVault.Acmebot.SharedFunctions.IssueCertificate(IDurableOrchestrationContext context) in D:\a\1\s\KeyVault.Acmebot\SharedFunctions.cs:line 75
  at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
  at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
  at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 86

**Comment by shibayan** [comment]
@raphael-liming Is a TXT record starting with `_acme-challenge` created in the relevant Azure DNS?

**Comment by raphael-liming** [comment]
No, they're not there at all. It looks like the function never puts it there,

**Comment by raphael-liming** [comment]
Do you think this would come down to a length issue of the subdomain plus the DNS Zone Name or something weird like that? Some of these domains and zones are very similar in length and exhibiting the same issue:
mlcheckout.oregononlinedriverimprovement.com
mlcheckout.virginiaonlinedriverimprovement.com

**Comment by shibayan** [comment]
There may be a problem on the Azure DNS side, so please try to create a TXT record manually once.

Ex. `_acme-challenge.dlwww.tennesseematuredriver.com `

**Comment by raphael-liming** [comment]
I did, and the record is there. Should I attempt again?

**Comment by shibayan** [comment]
Can the added host name be resolved with nslookup etc?  I couldn't get it right in my environment.

**Comment by raphael-liming** [comment]
It can be resolved with external dns on my side. From what I can tell, the function never adds the record to the DNS Zone Name to begin with. The DNS TXT record I placed wasn't updated with a new value from the function when I ran it.

**Comment by raphael-liming** [comment]
I've been successfully pulling them with a different certbot using these txt records on this Azure DNS Zone before:
https://crt.sh/?Identity=tennesseematuredriver.com&iCAID=16418

**Comment by shibayan** [comment]
Fixed the suspicious implementation, try overwriting the following key from Azure Functions Configuration. (I don’t know if it's fixed)

```json
{
  "name": "WEBSITE_RUN_FROM_PACKAGE",
  "value": "https://shibayan.blob.core.windows.net/azure-keyvault-letsencrypt/v3/latest.zip"
},
```

```json
{
  "name": "FUNCTIONS_EXTENSION_VERSION",
  "value": "~3"
},
```

**Comment by raphael-liming** [comment]
Looks like that fixed my issue. Thanks!
